### ISSUE TITLE
Link to source code repo in documentation

### ISSUE THREAD

**Issue by shawnthompson** [cenw-wscoe/sgdc-cdts#1]
Add a paragraph on the README.md page to talk about the source code repo https://github.com/wet-boew/cdts-sgdc/

> Please see [wet-boew](https://github.com/wet-boew/cdts-sgdc/) for the source code of the Centrally Deployed Templates Solution (CDTS) project.

**Comment by MaximPerry** [comment]
This was done 2 weeks ago, closing issue.
