### ISSUE TITLE
Translations needed.

### ISSUE THREAD

**Issue by shawnthompson** [cenw-wscoe/sgdc-cdts#13]
This issue is started to keep track of translation @MaximPerry needs to do in the repo.

New Comment added for each new translation.

**Comment by shawnthompson** [comment]
/docs/intranet-en.html - approx. line 712
> optional - subLinks - This variable is used with menuLinks to create a sub-menu in the main menu. The id value is manditory when using a the subLinks array.

**Comment by shawnthompson** [comment]
/docs/internet-en.html approx. line 192

>Optional - webAnalytics – Use this variable to include Adobe Analytics (AA).
> * Mandatory - environment – Use this value to state if the AA running is either staging or production.
> * Mandatory - version – Use this value to state which version of AA your application / site uses. Presently only versions 1 or 2 are available.

**Comment by shawnthompson** [comment]
/docs/intranet-en.html - approx. line 257

> Optional - GCToolsModal - This variable is used to make the GC Tools links in the header into a modal dialogue box. The default it set to false.

**Comment by MaximPerry** [comment]
Was there any more or should I push now and close this issue?

**Comment by shawnthompson** [comment]
you can push and close the issue. Thanks
