### ISSUE TITLE
Docs [CDTS-enabled web assets] link 404-ing, missing enabled-*.html

### ISSUE THREAD

**Issue by TeamDman** [cenw-wscoe/sgdc-cdts#21]
https://cenw-wscoe.github.io/sgdc-cdts/docs/index-en.html#Demo_pages
Who uses the CDTS? => CDTS-enabled web assets
Page doesn't exist

**Comment by shawnthompson** [comment]
That link it a Government of Canada that sits behind a firewall. We will add information to the links that sit behind our firewall. 

Thanks for letting us know.

**Comment by shawnthompson** [comment]
I spoke to soon. It should go to our GCPedia page. We will fix that link.
